server.port=1111



spring.datasource.url=jdbc:mysql://localhost:3306/dcbapp
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto:update
spring.jpa.show-sql=true

welmsg="em ra bob"